baseURL = "https://yidaofeicn.github.io/"	#网站基础地址
Title = " 易道非 Blog"				#名称
Theme ="flybirdNext"				#开发主题


LanguageCode = "zh-CN"
HasCJKLanguage = true
summaryLength=75					#简介长度，文章中可以使用 <!--more--> 指定呈现的内容
enableEmoji=true    				#是否启用表情
paginate = 10						#分页
googleAnalytics ="UA-126184892-2"	#google分析 

#Blackfriday配置
[blackfriday]
	angledQuotes = true
	fractions = false
	plainIDAnchors = true
	extensions = ["hardLineBreak"]
 
[Params] 
	isDevMode=false				#是否开启开发模式-主要定位页面使用
	DateFormat = "May 1,2006"		#日期格式化
	archive-paginate=10        	#分类、标签分页 
	rssFullContent=true
	busuanzi=true

	#导航部分设置
	logoImgPath="/image/logo.png"		#logo图片存放地址
	openSearch=true						#开启搜索
	#全局内容设置
	Keywords="software、易道非、飞雪"                 #关键词配置 
	authorName="易道非"
	lifeMotto="道可道，非常道，名可名，非常名"		  #人生格言 
	copyrightURL="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh"
	copyrightName="© 自由转载-非商用-非衍生-保持署名" 
	email="yidaofeicn@gmail.com"
	rss=true
	githubURL="https://github.com/yidaofeicn"

#utterances 评论系统
[Params.utteranc]
	enable=true
	repo = "yidaofeicn/yidaofeicnHugoBlog-utterances"
	issueTerm = "pathname"
#disqus 评论
disqusShortname = ""       

#计数器




 

[Menu]
  [[Menu.Main]]
    Name = "Home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "Categories"
    URL = "/categories/"
    Weight = 2
  [[Menu.Main]]
    Name = "Tags"
    URL = "/tags"
    Weight = 3
  [[Menu.Main]]
    Name = "Wiki"
    URL = "/wiki"
    Weight = 4
  [[Menu.Main]]
    Name = "About"
    URL = "/about"
    Weight = 5