baseURL = "https://yidaofei.com/"	#网站基础地址
Title = " 易道非 Blog"				#名称
Theme ="flybirdNext"				#开发主题

LanguageCode = "zh-CN"
HasCJKLanguage = true
summaryLength=120					#简介长度，文章中可以使用 <!--more--> 指定呈现的内容
enableEmoji=true    				#是否启用表情
paginate = 10						#分页
googleAnalytics ="xxxxxx"	#google分析 

#Blackfriday配置
[blackfriday]
	angledQuotes = true
	fractions = false
	plainIDAnchors = true

 
[Params] 
	isDevMode=false				#是否开启开发模式-主要定位页面使用
	DateFormat = "2006年01月02日"		#日期格式化
	archive-paginate=10        	#分类、标签分页 
	rssFullContent=true
	busuanzi=true
	favicon="/image/favicon-32x32.png"
	#导航部分设置
	logoImgPath="/image/logo.png"		#logo图片存放地址
	openSearch=true						#开启搜索
	#全局内容设置
	Keywords="software、易道非、飞雪"                 #关键词配置  
	 


#utterances 评论系统
[Params.utteranc]
	enable=true
	repo = "xxxxxx"
	issueTerm = "pathname"


#algolia 搜索
[Params.algolia]
	AppID="xxxxxx"
	SearchKey="xxxxxx"
	initIndex="xxxxxx"
#文章转载权限等
[Params.articleAuth]
	author="易道非"
 	CopyrightStatement="本博客所有文章除特别声明外，均采用 <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh'>[CC BY-NC-SA 4.0 CN ]</a> 许可协议。转载请注明出处！"
[Params.siteAuth]
	copyrightStatement="Copyright© 2018 Transparent Thoughts. All rights reserved."
[Params.social]
	email="xxxxxx" 
	github="xxxxxx"



 

[Menu]
  [[Menu.Main]]
    Name = "Home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "Categories"
    URL = "/categories/"
    Weight = 2
  [[Menu.Main]]
    Name = "Tags"
    URL = "/tags"
    Weight = 3
  [[Menu.Main]]
    Name = "Wiki"
    URL = "/wiki"
    Weight = 4
  [[Menu.Main]]
    Name = "About"
    URL = "/about"
    Weight = 5